### PR TITLE
Add Cursor.TryFind to hamsterdb-dotnet

### PR DESCRIPTION
**Pull request by mjmckp**
Existing method Cursor.Find throws an exception when input key is not
found.  Cursor.TryFind returns a boolean value indicating whether or not
the key was found.

### CODE REVIEW

**Comment by cruppstahl** [comment]
Wouldn't it be nicer if TryFind returns null in case of an error? Then the "ok" variable would not be required.

**Comment by mjmckp** [comment]
I was attempting to follow the pattern used by the TryGetValue method on System.Collections.Generic.Dictionary (https://msdn.microsoft.com/en-us/library/bb347013(v=vs.110).aspx).  I don't mind either way, really, it's up to you?

**Comment by cruppstahl** [comment]
As far as I understand the documentation, TryGetValue cannot return null
because it will return the initial value if the key does not exist. In
Cursor.TryFind() that's not possible because the value is not passed as a
parameter. So I think it's more convenient for users if TryFind returns
null in case of an error or if the key was not found.

So yes, if you have time to change it then please do so, otherwise I'll
rewrite the patch (you're not the first one who requires an exception-free
version of Find).

Thanks!
Christoph

2015-01-21 0:49 GMT+01:00 mjmckp <notifications@github.com>:

**Comment by mjmckp** [comment]
No problem, see latest commit.

Btw, have you considered adding a batch put/get methods, such as described for BDB [here](http://docs.oracle.com/cd/E17076_02/html/programmer_reference/am_misc_bulk.html)?  This would be particularly useful in the .NET wrapper, where the interop overhead of individual puts and gets becomes quite significant.

**Comment by cruppstahl** [comment]
Thanks for the patch!

I have thought about bulk operations, and they're on my TODO list. But in order to make them really fast i have to reorganize the code internally, which will take a while. So please don't hold your breath.

**Pull request merged**
